# Generated by Django 2.2.24 on 2023-02-27 17:23

from django.db import migrations


def fill_new_buildings(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_buildings=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_buildings=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_buildings)
    ]
