# Generated by Django 2.2.24 on 2023-03-02 15:38

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(owner=flat.owner, 
                                    owner_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner)
    ]
