# Generated by Django 2.2.24 on 2023-03-02 16:03

from django.db import migrations


def associate_flat_with_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230302_1838'),
    ]

    operations = [
            migrations.RunPython(associate_flat_with_owner)
    ]
