# Generated by Django 2.2.24 on 2023-03-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20230303_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat_owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
